"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var node_emoji_1 = require("node-emoji");
var chalk = require('chalk');
exports.EMOJIS = {
    KEY: node_emoji_1.get('key'),
    LOCK: node_emoji_1.get('lock'),
    UNLOCK: node_emoji_1.get('unlock'),
    LOCK_PEN: node_emoji_1.get('lock_with_ink_pen'),
    LOCK_KEY: node_emoji_1.get('closed_lock_with_key'),
    PERSON: node_emoji_1.get('bust_in_silhouette'),
    EMAIL: node_emoji_1.get('email'),
    PAGE: node_emoji_1.get('page_facing_up'),
    SERVER: node_emoji_1.get('desktop_computer'),
    INFO_DESK: node_emoji_1.get('information_desk_person'),
    RED_CIRCLE: node_emoji_1.get('red_circle'),
    TICK_MARK: node_emoji_1.get('white_check_mark'),
    EXCLAMATION: node_emoji_1.get('heavy_exclamation_mark'),
    WARNING: node_emoji_1.get('warning'),
    RELIEVED: node_emoji_1.get('relieved'),
    CONFUSED: node_emoji_1.get('confused'),
    HEART: node_emoji_1.get('heart'),
    COFFEE: node_emoji_1.get('coffee'),
    BEER: node_emoji_1.get('beer'),
    BROKEN_HEART: node_emoji_1.get('broken_heart'),
    CRYING: node_emoji_1.get('crying_cat_face'),
    HEART_EYES: node_emoji_1.get('heart_eyes_cat'),
    JOY: node_emoji_1.get('joy_cat'),
    KISSING: node_emoji_1.get('kissing_cat'),
    SCREAM: node_emoji_1.get('scream_cat'),
    ROCKET: node_emoji_1.get('rocket'),
    SMIRK: node_emoji_1.get('smirk_cat'),
    RAISED_HANDS: node_emoji_1.get('raised_hands'),
    POINT_RIGHT: node_emoji_1.get('point_right'),
    ZAP: node_emoji_1.get('zap'),
    BOOM: node_emoji_1.get('boom'),
    PRAY: node_emoji_1.get('pray'),
    WINE: node_emoji_1.get('wine_glass'),
};
exports.MESSAGES = {
    ASK_EMAIL: exports.EMOJIS.EMAIL + "  Enter your registered e-mail address:",
    ASK_EMAIL_ERR: exports.EMOJIS.RED_CIRCLE + "  " + chalk.red('Please enter your username or e-mail address.'),
    ASK_PWD: exports.EMOJIS.KEY + " " + chalk.greenBright('Enter your password:'),
    ASK_PWD_ERR: exports.EMOJIS.RED_CIRCLE + "  " + chalk.red('Please enter your password'),
    ASK_SERVER_ADDRS: exports.EMOJIS.SERVER + "  Enter full address of the sphinx server:",
    ASK_SERVER_ADDRS_ERR: exports.EMOJIS.RED_CIRCLE + "  " + chalk.red('Please enter a valid url'),
    ASK_NAME: exports.EMOJIS.INFO_DESK + "  Enter your name:",
    KEY_ROTATION_WARNING: exports.EMOJIS.WARNING + "  " + chalk.redBright("WARNING: You won't be able to read your existing secrets after key rotation"),
    ASK_SURE: "" + chalk.yellowBright('Are you sure you want to proceed?'),
    KEY_ROTATION_SUCCESS: exports.EMOJIS.TICK_MARK + "  " + chalk.greenBright('Key rotation successfull'),
    KEY_ROTATION_ABORT: exports.EMOJIS.RELIEVED + "  " + chalk.greenBright('Key rotation aborted'),
    INVALID_INPUT: exports.EMOJIS.RED_CIRCLE + "  " + chalk.red('Invalid input'),
    RESOURCE_INVALID: function (res) { return exports.EMOJIS.CONFUSED + "  " + chalk.red("Invalid <resource> type " + chalk.redBright(res)); },
};
