export declare const EMOJIS: {
    KEY: string;
    LOCK: string;
    UNLOCK: string;
    LOCK_PEN: string;
    LOCK_KEY: string;
    PERSON: string;
    EMAIL: string;
    PAGE: string;
    SERVER: string;
    INFO_DESK: string;
    RED_CIRCLE: string;
    TICK_MARK: string;
    EXCLAMATION: string;
    WARNING: string;
    RELIEVED: string;
    CONFUSED: string;
    SMILE: string;
    HOURGLASS: string;
    HEART: string;
    COFFEE: string;
    BEER: string;
    BROKEN_HEART: string;
    CRYING: string;
    HEART_EYES: string;
    JOY: string;
    KISSING: string;
    SCREAM: string;
    ROCKET: string;
    SMIRK: string;
    RAISED_HANDS: string;
    POINT_RIGHT: string;
    ZAP: string;
    BOOM: string;
    PRAY: string;
    WINE: string;
};
export declare const MESSAGES: {
    ASK_EMAIL: string;
    ASK_EMAIL_ERR: string;
    ASK_PWD: string;
    ASK_PWD_ERR: string;
    ASK_SERVER_ADDRS: string;
    ASK_SERVER_ADDRS_ERR: string;
    ASK_NAME: string;
    KEY_ROTATION_WARNING: string;
    ASK_SURE: string;
    KEY_ROTATION_SUCCESS: string;
    KEY_ROTATION_ABORT: string;
    INVALID_INPUT: string;
    SECRET_SUCCESS: string;
    ASK_RECIPIENT: string;
    ASK_SECRET_NAME: string;
    ASK_SECRET: string;
    ASK_DESC: string;
    ASK_TTL: string;
    ASK_SELECT_SECRET: string;
    SECRET_CHOICE: (secret: any) => string;
    RESOURCE_INVALID: (res: string) => string;
};
